### ISSUE TITLE
Title of this page: http://www.conversaschool.nl/mission/

### ISSUE THREAD

**Issue by pandusia** [conversataal/conversataal.github.io#8]
is Conversa School | undefined.

 
Please change it to Conversa School | Mission

**Comment by mdvanes** [comment]
Good find. Please be advised this is visible to the entire world, because your screenshot contained private information.

Solution probably: https://github.com/gatsbyjs/gatsby-starter-kitchen-sink/blob/master/pages/html.html

**Comment by pandusia** [comment]
Have you removed it, please? Xxx
